PROJECTROOT  = ..
BUILDROOT    = ../build/
PROJECT      = cshared
DEBUG        = yes
testdir      = tests

alibs        = $(PROJECT)
solibs       = $(PROJECT)

sources       := copts.c cserialize.c cstr.c cring.c e4c_lite.c
sources-WIN32 := cdir_win.c
headers       := copts.h cserialize.h cstr.h cdir.h cring.h e4c_lite.h
tests         := test_copts.c

include ../common.mk
